# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md
fos_elastica:
    clients:
        default: { host: elasticsearch, port: 9200 }
    indexes:
        category:
            finder: ~
            client: default
            types:
              category:
                properties:
                  id: ~
                  name: ~
                persistence:
                  driver: orm
                  model: App\Infrastructure\Category\Query\Projections\CategoryView
                  provider: ~
                  finder: ~
                  repository: App\Infrastructure\Category\Repository\CategoryFosElasticaRepository
        fos_user:
          finder: ~
          client: default
          types:
            fos_user:
              properties:
                id: ~
                username: ~
                email: ~
                roles: ~
                enabled: ~
                avatar: ~
                steemit: ~
                banned: ~
              persistence:
                driver: orm
                model: App\Infrastructure\User\Query\Projections\UserView
                provider: ~
                finder: ~
                repository: App\Infrastructure\User\Repository\UserFosElasticaRepository

        post:
          finder: ~
          client: default
          types:
            post:
              properties:
                id: ~
                title: ~
                content: ~
                thumbnail: ~
                slug: ~
                shortDescription: ~
                createdAt: { type: date}
                type: ~
                user: ~
                category: ~
              persistence:
                driver: orm
                model: App\Infrastructure\Post\Query\Projections\PostView
                provider: ~
                finder: ~
                repository: App\Infrastructure\Post\Repository\Query\PostRepositoryElastic
        comment:
          finder: ~
          client: default
          types:
            comment:
              properties:
                id: ~
                content: ~
                parrentComment: ~
                post: ~
                user: ~
                createdAt: { type: date}
              persistence:
                driver: orm
                model: App\Infrastructure\Comment\Query\Projections\CommentView
                provider: ~
                finder: ~
                repository: App\Infrastructure\Comment\Query\CommentRepositoryElastic
        message:
          finder: ~
          client: default
          types:
            message:
              properties:
                id: ~
                content: ~
                displayed: ~
                sender: ~
                recipient: ~
                createdAt: { type: date}
              persistence:
                driver: orm
                model: App\Infrastructure\Message\MessageView
                provider: ~
                finder: ~
                repository: App\Infrastructure\Message\Query\MessageRepositoryElastic



