# Use root/example as user/password credentials
version: '3.1'

services:
  nginx:
    image: nginx:1.11-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - db
      - php


  php:
    build: ./docker/php
    working_dir: /var/www/project
    volumes:
      - ./:/var/www/project
    links:
      - db
    ports:
      - "8123:8123"

  workers:
    build: ./docker/php
    volumes:
    - ./:/var/www/project


  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: admin
    restart: always
    ports:
     - 8000:80
    volumes:
     - /sessions

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    ports:
      - 9200:9200
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms250m -Xmx250m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - esdata1:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    ports:
      - 5601:5601
    volumes:
      - ./docker/kibana/config:/usr/share/kibana/config/kibana.yml

#  rabbit:
#    image: "rabbitmq:3.7.8-management"
#    environment:
#      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
#      RABBITMQ_DEFAULT_USER: "admin"
#      RABBITMQ_DEFAULT_PASS: "admin"
#      RABBITMQ_DEFAULT_VHOST: "/"
#    ports:
#    - "15672:15672"
#    - "5672:5672"
#    labels:
#      NAME: "rabbitmq"

    
volumes:
  db_data:
  esdata1:
