# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    elastic:
        hosts:
          - '%env(ELASTIC_HOST)%'

    env(ELASTIC_HOST): 'elasticsearch:9200'

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
          $elasticConfig: '%elastic%'

          $queryBus: '@tactician.commandbus.query'
          $commandBus: '@tactician.commandbus.command'
          $eventBus: '@broadway.event_handling.event_bus'

          $eventStore: '@Broadway\EventStore\Dbal\DBALEventStore'

    _instanceof:

        App\Application\Command\CommandHandlerInterface:
            public: true
            tags:
                - { name: tactician.handler, typehints: true, bus: command }

        App\Application\Query\QueryHandlerInterface:
            public: true
            tags:
                - { name: tactician.handler, typehints: true, bus: query }

        Broadway\EventHandling\EventListener:
            public: true
            tags:
                - { name: broadway.domain.event_listener }

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\UI\HTTP\Rest\Controller\:
        resource: '../src/UI/HTTP/Rest/Controller'
        tags: ['controller.service_arguments']

    App\UI\HTTP\Rest\EventSubscriber\JsonBodyParserSubscriber:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest', priority: 100 }

    App\UI\HTTP\Rest\EventSubscriber\ExceptionSubscriber:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception' }
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Broadway\EventStore\Dbal\DBALEventStore:
        public: true
        arguments:
            - '@doctrine.dbal.default_connection'
            - '@broadway.serializer.payload'
            - '@broadway.serializer.metadata'
            - 'events'
            - 'false'
            - '@broadway.uuid.converter'
